package com.deemsys.project.entity;

// Generated Apr 23, 2016 6:04:02 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DocumentType generated by hbm2java
 */
@Entity
@Table(name = "document_type", catalog = "iqms")
public class DocumentType implements java.io.Serializable {

	private Integer docTypeId;
	private String docTypeName;
	private String docPrefix;
	private String description;
	private Integer status;

	public DocumentType() {
	}

	public DocumentType(String docTypeName, String docPrefix,
			String description, Integer status) {
		this.docTypeName = docTypeName;
		this.docPrefix = docPrefix;
		this.description = description;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "doc_type_id", unique = true, nullable = false)
	public Integer getDocTypeId() {
		return this.docTypeId;
	}

	public void setDocTypeId(Integer docTypeId) {
		this.docTypeId = docTypeId;
	}

	@Column(name = "doc_type_name", length = 80)
	public String getDocTypeName() {
		return this.docTypeName;
	}

	public void setDocTypeName(String docTypeName) {
		this.docTypeName = docTypeName;
	}

	@Column(name = "doc_prefix", length = 10)
	public String getDocPrefix() {
		return this.docPrefix;
	}

	public void setDocPrefix(String docPrefix) {
		this.docPrefix = docPrefix;
	}

	@Column(name = "description", length = 150)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
