package com.deemsys.project.entity;

// Generated Apr 23, 2016 6:04:02 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DocumentRevisionFormat generated by hbm2java
 */
@Entity
@Table(name = "document_revision_format", catalog = "iqms")
public class DocumentRevisionFormat implements java.io.Serializable {

	private Integer settingsId;
	private Integer formatPrefix;
	private Integer formatSuffix;

	public DocumentRevisionFormat() {
	}

	public DocumentRevisionFormat(Integer formatPrefix, Integer formatSuffix) {
		this.formatPrefix = formatPrefix;
		this.formatSuffix = formatSuffix;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "settings_id", unique = true, nullable = false)
	public Integer getSettingsId() {
		return this.settingsId;
	}

	public void setSettingsId(Integer settingsId) {
		this.settingsId = settingsId;
	}

	@Column(name = "format_prefix")
	public Integer getFormatPrefix() {
		return this.formatPrefix;
	}

	public void setFormatPrefix(Integer formatPrefix) {
		this.formatPrefix = formatPrefix;
	}

	@Column(name = "format_suffix")
	public Integer getFormatSuffix() {
		return this.formatSuffix;
	}

	public void setFormatSuffix(Integer formatSuffix) {
		this.formatSuffix = formatSuffix;
	}

}
