package com.deemsys.project.entity;

// Generated Apr 23, 2016 6:04:02 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DocumentLocation generated by hbm2java
 */
@Entity
@Table(name = "document_location", catalog = "iqms")
public class DocumentLocation implements java.io.Serializable {

	private Integer docLocationId;
	private String docLocation;
	private String description;
	private Integer status;

	public DocumentLocation() {
	}

	public DocumentLocation(String docLocation, String description,
			Integer status) {
		this.docLocation = docLocation;
		this.description = description;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "doc_location_id", unique = true, nullable = false)
	public Integer getDocLocationId() {
		return this.docLocationId;
	}

	public void setDocLocationId(Integer docLocationId) {
		this.docLocationId = docLocationId;
	}

	@Column(name = "doc_location", length = 80)
	public String getDocLocation() {
		return this.docLocation;
	}

	public void setDocLocation(String docLocation) {
		this.docLocation = docLocation;
	}

	@Column(name = "description", length = 150)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
