package com.deemsys.project.entity;

// Generated Apr 23, 2016 6:04:02 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EmailRecepients generated by hbm2java
 */
@Entity
@Table(name = "email_recepients", catalog = "iqms")
public class EmailRecepients implements java.io.Serializable {

	private EmailRecepientsId id;

	public EmailRecepients() {
	}

	public EmailRecepients(EmailRecepientsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "moduleId", column = @Column(name = "module_id", nullable = false)) })
	public EmailRecepientsId getId() {
		return this.id;
	}

	public void setId(EmailRecepientsId id) {
		this.id = id;
	}

}
