package com.deemsys.project.entity;

// Generated Apr 23, 2016 6:04:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HrTrainees generated by hbm2java
 */
@Entity
@Table(name = "hr_trainees", catalog = "iqms")
public class HrTrainees implements java.io.Serializable {

	private Integer hrTraineeId;
	private String hrEmpId;
	private String name;
	private Integer jobTitle;
	private Date dateHired;
	private Integer management;
	private Integer processOwner;
	private Integer documentControl;
	private String documentedIn;
	private Integer calibration;
	private Integer responsibility;
	private Integer disposition;
	private Integer qualifiedBy;
	private Integer typeOfTraining;
	private String trainer;
	private Date trainingDueDate;
	private Date trainingCompletionDate;
	private Date trainingEffectivenessReviewDueDate;
	private String trainingEffectivenessNotes;

	public HrTrainees() {
	}

	public HrTrainees(String hrEmpId, String name, Integer jobTitle,
			Date dateHired, Integer management, Integer processOwner,
			Integer documentControl, String documentedIn, Integer calibration,
			Integer responsibility, Integer disposition, Integer qualifiedBy,
			Integer typeOfTraining, String trainer, Date trainingDueDate,
			Date trainingCompletionDate,
			Date trainingEffectivenessReviewDueDate,
			String trainingEffectivenessNotes) {
		this.hrEmpId = hrEmpId;
		this.name = name;
		this.jobTitle = jobTitle;
		this.dateHired = dateHired;
		this.management = management;
		this.processOwner = processOwner;
		this.documentControl = documentControl;
		this.documentedIn = documentedIn;
		this.calibration = calibration;
		this.responsibility = responsibility;
		this.disposition = disposition;
		this.qualifiedBy = qualifiedBy;
		this.typeOfTraining = typeOfTraining;
		this.trainer = trainer;
		this.trainingDueDate = trainingDueDate;
		this.trainingCompletionDate = trainingCompletionDate;
		this.trainingEffectivenessReviewDueDate = trainingEffectivenessReviewDueDate;
		this.trainingEffectivenessNotes = trainingEffectivenessNotes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "hr_trainee_id", unique = true, nullable = false)
	public Integer getHrTraineeId() {
		return this.hrTraineeId;
	}

	public void setHrTraineeId(Integer hrTraineeId) {
		this.hrTraineeId = hrTraineeId;
	}

	@Column(name = "hr_emp_id", length = 45)
	public String getHrEmpId() {
		return this.hrEmpId;
	}

	public void setHrEmpId(String hrEmpId) {
		this.hrEmpId = hrEmpId;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "job_title")
	public Integer getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(Integer jobTitle) {
		this.jobTitle = jobTitle;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_hired", length = 10)
	public Date getDateHired() {
		return this.dateHired;
	}

	public void setDateHired(Date dateHired) {
		this.dateHired = dateHired;
	}

	@Column(name = "management")
	public Integer getManagement() {
		return this.management;
	}

	public void setManagement(Integer management) {
		this.management = management;
	}

	@Column(name = "process_owner")
	public Integer getProcessOwner() {
		return this.processOwner;
	}

	public void setProcessOwner(Integer processOwner) {
		this.processOwner = processOwner;
	}

	@Column(name = "document_control")
	public Integer getDocumentControl() {
		return this.documentControl;
	}

	public void setDocumentControl(Integer documentControl) {
		this.documentControl = documentControl;
	}

	@Column(name = "documented_in", length = 45)
	public String getDocumentedIn() {
		return this.documentedIn;
	}

	public void setDocumentedIn(String documentedIn) {
		this.documentedIn = documentedIn;
	}

	@Column(name = "calibration")
	public Integer getCalibration() {
		return this.calibration;
	}

	public void setCalibration(Integer calibration) {
		this.calibration = calibration;
	}

	@Column(name = "responsibility")
	public Integer getResponsibility() {
		return this.responsibility;
	}

	public void setResponsibility(Integer responsibility) {
		this.responsibility = responsibility;
	}

	@Column(name = "disposition")
	public Integer getDisposition() {
		return this.disposition;
	}

	public void setDisposition(Integer disposition) {
		this.disposition = disposition;
	}

	@Column(name = "qualified_by")
	public Integer getQualifiedBy() {
		return this.qualifiedBy;
	}

	public void setQualifiedBy(Integer qualifiedBy) {
		this.qualifiedBy = qualifiedBy;
	}

	@Column(name = "type_of_training")
	public Integer getTypeOfTraining() {
		return this.typeOfTraining;
	}

	public void setTypeOfTraining(Integer typeOfTraining) {
		this.typeOfTraining = typeOfTraining;
	}

	@Column(name = "trainer", length = 45)
	public String getTrainer() {
		return this.trainer;
	}

	public void setTrainer(String trainer) {
		this.trainer = trainer;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "training_due_date", length = 10)
	public Date getTrainingDueDate() {
		return this.trainingDueDate;
	}

	public void setTrainingDueDate(Date trainingDueDate) {
		this.trainingDueDate = trainingDueDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "training_completion_date", length = 10)
	public Date getTrainingCompletionDate() {
		return this.trainingCompletionDate;
	}

	public void setTrainingCompletionDate(Date trainingCompletionDate) {
		this.trainingCompletionDate = trainingCompletionDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "training_effectiveness_review_due_date", length = 10)
	public Date getTrainingEffectivenessReviewDueDate() {
		return this.trainingEffectivenessReviewDueDate;
	}

	public void setTrainingEffectivenessReviewDueDate(
			Date trainingEffectivenessReviewDueDate) {
		this.trainingEffectivenessReviewDueDate = trainingEffectivenessReviewDueDate;
	}

	@Column(name = "training_effectiveness_notes", length = 250)
	public String getTrainingEffectivenessNotes() {
		return this.trainingEffectivenessNotes;
	}

	public void setTrainingEffectivenessNotes(String trainingEffectivenessNotes) {
		this.trainingEffectivenessNotes = trainingEffectivenessNotes;
	}

}
