package com.deemsys.project.entity;

// Generated May 25, 2016 11:36:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Job generated by hbm2java
 */
@Entity
@Table(name = "job", catalog = "innova")
public class Job implements java.io.Serializable {

	private Long jobId;
	private JobCategory jobCategory;
	private String name;
	private String description;
	private Date addedDate;
	private Integer isEnable;
	private Integer status;
	private Set<JobTagMap> jobTagMaps = new HashSet<JobTagMap>(0);

	public Job() {
	}

	public Job(JobCategory jobCategory, String name, String description,
			Date addedDate, Integer isEnable, Integer status,
			Set<JobTagMap> jobTagMaps) {
		this.jobCategory = jobCategory;
		this.name = name;
		this.description = description;
		this.addedDate = addedDate;
		this.isEnable = isEnable;
		this.status = status;
		this.jobTagMaps = jobTagMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "job_id", unique = true, nullable = false)
	public Long getJobId() {
		return this.jobId;
	}

	public void setJobId(Long jobId) {
		this.jobId = jobId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "job_category_id")
	public JobCategory getJobCategory() {
		return this.jobCategory;
	}

	public void setJobCategory(JobCategory jobCategory) {
		this.jobCategory = jobCategory;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 600)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "added_date", length = 10)
	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	@Column(name = "is_enable")
	public Integer getIsEnable() {
		return this.isEnable;
	}

	public void setIsEnable(Integer isEnable) {
		this.isEnable = isEnable;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "job")
	public Set<JobTagMap> getJobTagMaps() {
		return this.jobTagMaps;
	}

	public void setJobTagMaps(Set<JobTagMap> jobTagMaps) {
		this.jobTagMaps = jobTagMaps;
	}

}
