package com.deemsys.project.entity;

// Generated May 26, 2016 2:42:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JobSeeker generated by hbm2java
 */
@Entity
@Table(name = "job_seeker", catalog = "innova")
public class JobSeeker implements java.io.Serializable {

	private String jobSeekerId;
	private String firstName;
	private String lastName;
	private String email;
	private String phoneNumber;
	private Integer status;
	private String resumeName;
	private String resumeType;

	public JobSeeker() {
	}

	public JobSeeker(String jobSeekerId) {
		this.jobSeekerId = jobSeekerId;
	}

	public JobSeeker(String jobSeekerId, String firstName, String lastName,
			String email, String phoneNumber, Integer status,
			String resumeName, String resumeType) {
		this.jobSeekerId = jobSeekerId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.status = status;
		this.resumeName = resumeName;
		this.resumeType = resumeType;
	}

	@Id
	@Column(name = "job_seeker_id", unique = true, nullable = false, length = 32)
	public String getJobSeekerId() {
		return this.jobSeekerId;
	}

	public void setJobSeekerId(String jobSeekerId) {
		this.jobSeekerId = jobSeekerId;
	}

	@Column(name = "first_name", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email", length = 60)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone_number", length = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "resume_name", length = 200)
	public String getResumeName() {
		return this.resumeName;
	}

	public void setResumeName(String resumeName) {
		this.resumeName = resumeName;
	}

	@Column(name = "resume_type", length = 100)
	public String getResumeType() {
		return this.resumeType;
	}

	public void setResumeType(String resumeType) {
		this.resumeType = resumeType;
	}

}
