package com.deemsys.project.entity;

// Generated May 26, 2016 2:42:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobSeeker generated by hbm2java
 */
@Entity
@Table(name = "job_seeker", catalog = "innova")
public class JobSeeker implements java.io.Serializable {

	private String jobSeekerId;
	private String firstName;
	private String lastName;
	private String email;
	private String phoneNumber;
	private String interestedIn;
	private String resumeName;
	private String resumeType;
	private Date dateTime;
	private Integer status;
	

	public JobSeeker() {
	}

	public JobSeeker(String jobSeekerId) {
		this.jobSeekerId = jobSeekerId;
	}

	public JobSeeker(String jobSeekerId, String firstName, String lastName,
			String email, String phoneNumber, String interestedIn, String resumeName, 
			String resumeType, Date dateTime, Integer status) {
		this.jobSeekerId = jobSeekerId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.interestedIn = interestedIn;
		this.resumeName = resumeName;
		this.resumeType = resumeType;
		this.dateTime = dateTime;
		this.status = status;
		
	}

	@Id
	@Column(name = "job_seeker_id", unique = true, nullable = false, length = 32)
	public String getJobSeekerId() {
		return this.jobSeekerId;
	}

	public void setJobSeekerId(String jobSeekerId) {
		this.jobSeekerId = jobSeekerId;
	}

	@Column(name = "first_name", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email", length = 60)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone_number", length = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "interested_in", length = 100)
	public String getInterestedIn() {
		return interestedIn;
	}

	public void setInterestedIn(String interestedIn) {
		this.interestedIn = interestedIn;
	}

	@Column(name = "resume_name", length = 200)
	public String getResumeName() {
		return this.resumeName;
	}

	public void setResumeName(String resumeName) {
		this.resumeName = resumeName;
	}

	@Column(name = "resume_type", length = 100)
	public String getResumeType() {
		return this.resumeType;
	}

	public void setResumeType(String resumeType) {
		this.resumeType = resumeType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_time", length = 19)
	public Date getDateTime() {
		return dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	
}
