package com.deemsys.project.entity;

// Generated May 24, 2016 3:57:03 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * JobTagId generated by hbm2java
 */
@Embeddable
public class JobTagId implements java.io.Serializable {

	private Long jobId;
	private String tags;
	private Integer status;

	public JobTagId() {
	}

	public JobTagId(Long jobId, String tags, Integer status) {
		this.jobId = jobId;
		this.tags = tags;
		this.status = status;
	}

	@Column(name = "job_id")
	public Long getJobId() {
		return this.jobId;
	}

	public void setJobId(Long jobId) {
		this.jobId = jobId;
	}

	@Column(name = "tags", length = 60)
	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JobTagId))
			return false;
		JobTagId castOther = (JobTagId) other;

		return ((this.getJobId() == castOther.getJobId()) || (this.getJobId() != null
				&& castOther.getJobId() != null && this.getJobId().equals(
				castOther.getJobId())))
				&& ((this.getTags() == castOther.getTags()) || (this.getTags() != null
						&& castOther.getTags() != null && this.getTags()
						.equals(castOther.getTags())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getJobId() == null ? 0 : this.getJobId().hashCode());
		result = 37 * result
				+ (getTags() == null ? 0 : this.getTags().hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		return result;
	}

}
