package com.deemsys.project.entity;

// Generated May 25, 2016 11:36:39 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * JobTagMapId generated by hbm2java
 */
@Embeddable
public class JobTagMapId implements java.io.Serializable {

	private Long jobId;
	private Long tagId;
	private Integer status;

	public JobTagMapId() {
	}

	public JobTagMapId(Long jobId, Long tagId, Integer status) {
		this.jobId = jobId;
		this.tagId = tagId;
		this.status = status;
	}

	@Column(name = "job_id")
	public Long getJobId() {
		return this.jobId;
	}

	public void setJobId(Long jobId) {
		this.jobId = jobId;
	}

	@Column(name = "tag_id")
	public Long getTagId() {
		return this.tagId;
	}

	public void setTagId(Long tagId) {
		this.tagId = tagId;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JobTagMapId))
			return false;
		JobTagMapId castOther = (JobTagMapId) other;

		return ((this.getJobId() == castOther.getJobId()) || (this.getJobId() != null
				&& castOther.getJobId() != null && this.getJobId().equals(
				castOther.getJobId())))
				&& ((this.getTagId() == castOther.getTagId()) || (this
						.getTagId() != null && castOther.getTagId() != null && this
						.getTagId().equals(castOther.getTagId())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getJobId() == null ? 0 : this.getJobId().hashCode());
		result = 37 * result
				+ (getTagId() == null ? 0 : this.getTagId().hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		return result;
	}

}
