package com.deemsys.project.entity;

// Generated May 26, 2016 2:42:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobTags generated by hbm2java
 */
@Entity
@Table(name = "job_tags", catalog = "innova")
public class JobTags implements java.io.Serializable {

	private Long tagId;
	private String tagName;
	private Date addedDate;
	private Integer status;
	private Set<JobTagMap> jobTagMaps = new HashSet<JobTagMap>(0);

	public JobTags() {
	}

	public JobTags(String tagName, Date addedDate, Integer status,
			Set<JobTagMap> jobTagMaps) {
		this.tagName = tagName;
		this.addedDate = addedDate;
		this.status = status;
		this.jobTagMaps = jobTagMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tag_id", unique = true, nullable = false)
	public Long getTagId() {
		return this.tagId;
	}

	public void setTagId(Long tagId) {
		this.tagId = tagId;
	}

	@Column(name = "tag_name", length = 60)
	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "added_date", length = 10)
	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobTags")
	public Set<JobTagMap> getJobTagMaps() {
		return this.jobTagMaps;
	}

	public void setJobTagMaps(Set<JobTagMap> jobTagMaps) {
		this.jobTagMaps = jobTagMaps;
	}

}
