package com.deemsys.project.entity;

// Generated May 24, 2016 3:57:03 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JobTag generated by hbm2java
 */
@Entity
@Table(name = "job_tag", catalog = "innova")
public class JobTag implements java.io.Serializable {

	private JobTagId id;
	private Job job;

	public JobTag() {
	}

	public JobTag(JobTagId id) {
		this.id = id;
	}

	public JobTag(JobTagId id, Job job) {
		this.id = id;
		this.job = job;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "jobId", column = @Column(name = "job_id")),
			@AttributeOverride(name = "tags", column = @Column(name = "tags", length = 60)),
			@AttributeOverride(name = "status", column = @Column(name = "status")) })
	public JobTagId getId() {
		return this.id;
	}

	public void setId(JobTagId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "job_id", insertable = false, updatable = false)
	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

}
