package com.deemsys.project.entity;

// Generated Apr 23, 2016 6:04:02 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Modules generated by hbm2java
 */
@Entity
@Table(name = "modules", catalog = "iqms")
public class Modules implements java.io.Serializable {

	private Integer moduleId;
	private String module;

	public Modules() {
	}

	public Modules(String module) {
		this.module = module;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "module_id", unique = true, nullable = false)
	public Integer getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	@Column(name = "module", length = 100)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
