package com.deemsys.project.entity;

// Generated May 25, 2016 11:36:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ResumeDetail generated by hbm2java
 */
@Entity
@Table(name = "resume_detail", catalog = "innova")
public class ResumeDetail implements java.io.Serializable {

	private String resumeId;
	private String name;
	private String type;
	private String reference;
	private Integer status;
	private Set<JobSeeker> jobSeekers = new HashSet<JobSeeker>(0);

	public ResumeDetail() {
	}

	public ResumeDetail(String resumeId) {
		this.resumeId = resumeId;
	}

	public ResumeDetail(String resumeId, String name, String type,
			String reference, Integer status, Set<JobSeeker> jobSeekers) {
		this.resumeId = resumeId;
		this.name = name;
		this.type = type;
		this.reference = reference;
		this.status = status;
		this.jobSeekers = jobSeekers;
	}

	@Id
	@Column(name = "resume_id", unique = true, nullable = false, length = 32)
	public String getResumeId() {
		return this.resumeId;
	}

	public void setResumeId(String resumeId) {
		this.resumeId = resumeId;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type", length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "reference", length = 150)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resumeDetail")
	public Set<JobSeeker> getJobSeekers() {
		return this.jobSeekers;
	}

	public void setJobSeekers(Set<JobSeeker> jobSeekers) {
		this.jobSeekers = jobSeekers;
	}

}
