package com.deemsys.project.entity;

// Generated May 23, 2016 4:52:30 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Testimonial generated by hbm2java
 */
@Entity
@Table(name = "testimonial", catalog = "innova")
public class Testimonial implements java.io.Serializable {

	private Long testimonialId;
	private String description;
	private String saidBy;
	private String destination;
	private Integer status;

	public Testimonial() {
	}

	public Testimonial(String description, String saidBy, String destination,
			Integer status) {
		this.description = description;
		this.saidBy = saidBy;
		this.destination = destination;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "testimonial_id", unique = true, nullable = false)
	public Long getTestimonialId() {
		return this.testimonialId;
	}

	public void setTestimonialId(Long testimonialId) {
		this.testimonialId = testimonialId;
	}

	@Column(name = "description", length = 800)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "said_by", length = 45)
	public String getSaidBy() {
		return this.saidBy;
	}

	public void setSaidBy(String saidBy) {
		this.saidBy = saidBy;
	}

	@Column(name = "destination", length = 45)
	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
